const languageData = {
  English: {
    title: "Unlimited movies, TV shows and more",
    subtitle: "Starts at ₹149. Cancel at any time.",
    description:
      "Ready to watch? Enter your email to create or restart your membership.",
    email: "Email address",
    Aemail: "Email",
    validEmail: "Please enter a valid email address.",
    requiredEmail: "Email is required.",
    getStarted: "Get Started",
    signIn: "Sign In",
    trendingNow: "Trending Now",
    faq: "Frequently Asked Questions",
    moreReasons: "More reasons to join",
    passwordLength: "Your password must contain between 6 and 60 characters.",
    forgetPassword: "Forgot Password?",
    resetPassword: "How would you like to reset your password?",
    resetPasswordByEmail:
      "We will send you an email with instructions on how to reset your password.",
    resetPasswordByText:
      "We will send you a text message with instructions on how to reset your password.",
    enterValidPhoneNumber: "Please enter a valid phone number.",
    enterValidEmailAndMobile: "Please enter a valid email or phone number.",
    sendPasswordResetCode: "Send sign-in code",
    passwordUpdated: "Password updated successfully.",
    signInCodeSent: "A sign-in code has been sent to your email.",
    emailMe: "Email Me",
    messageMe: "Message Me",
    choosePlan: "Choose your plan",
    planDetails:
      "No commitments, cancel anytime. Everything on Netflix for one low price. No ads and no extra fees.",
    skip: "Skip",
    chooseTheRightPlan: "Choose the plan that’s right for you",
    choosePlanTitle: "Choose your plan.",
    paymentSecurityInfo:
      "Your payment is encrypted and you can change your payment method at any time.",
    securePeaceOfMind: "Secure for peace of mind.",
    cancelEasilyOnline: "Cancel easily online.",
    endToEndEncrypted: "End-to-end encrypted",
    creditOrDebitCard: "Credit or Debit card",
    upiAutoPay: "UPI AutoPay",
    paymentCompleted: "Payment Completed",
    readyToWatch: "Ready to Watch!",
    whoIsWatching: "Who's watching?",
    addProfile: "Add Profile",
    manageProfiles: "Manage Profiles",
    browse: "Browse",
    signOut: "Sign out of Netflix",
    serviceCode: "Service Code",
    play: "Play",
    moreInfo: "More info",
    myList: "My List",
    noTitlesInList: "You haven't added any titles to your list yet.",
    removedFromList: "has been removed from my list.",
    undo: "Undo",
    netflixIndia: "Netflix India",
    signout: "Sign Out",
    finishSettingUpAccount: "Finish setting up your account",
    personalizedNetflix:
      "Netflix is personalised for you. Create a password to watch on any device at any time.",
    next: "Next",
    createPasswordNetflix: "Create a password to start your membership.",
    fewStepsNetflix: "Just a few more steps and you're done!",
    paperworkNetflix: "We hate paperwork, too.",
    emailOrMobileNetflix: "Email or mobile number",
    passwordNetflix: "Password",
    verifyEmailNetflix: "Great, now let us verify your email.",
    messageDataRatesNetflix: "Message and data rates may apply",
    orNetflix: "or",
    usePasswordNetflix: "Use password",
    useSignInCodeNetflix: "Use a sign-in code",
    rememberMeNetflix: "Remember me",
    newToNetflix: "New to Netflix?",
    signUpNowNetflix: "Sign Up now",
    recaptchaProtectionNetflix:
      "This page is protected by Google reCAPTCHA to ensure you're not a bot.",
    learnMoreNetflix: "Learn more.",
    updatePasswordEmailPhoneNetflix: "Update password, email or phone",
    textMessageSMS: "Text Message (SMS)",
    verificationCodeMessage:
      "We will text you a verification code to reset your password. Message and data rates may apply.",
    mobileNumber: "Mobile number",
    step: "STEP",
    of: "of",
    verifyingEmailMessage:
      "Verifying your email will improve account security and help you receive important Netflix communications.",
    
  },
  Hindi: {
    title: "अनलिमिटेड फिल्में, टीवी शो और बहुत कुछ",
    subtitle: "₹149 से शुरू। कभी भी रद्द करें।",
    description:
      "देखने के लिए तैयार हैं? अपनी सदस्यता शुरू करने या फिर से शुरू करने के लिए अपना ईमेल दर्ज करें।",
    email: "ईमेल पता",
    Aemail: "ईमेल",
    validEmail: "कृपया एक वैध ईमेल पता दर्ज करें।",
    requiredEmail: "ईमेल आवश्यक है।",
    getStarted: "शुरू करें",
    signIn: "साइन इन करें",
    trendingNow: "अब ट्रेंडिंग",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    moreReasons: "जोड़ने के अधिक कारण",
    passwordLength: "आपका पासवर्ड 6 से 60 वर्णों के बीच होना चाहिए।",
    forgetPassword: "पासवर्ड भूल गए?",
    resetPassword: "आप अपना पासवर्ड कैसे रीसेट करना चाहेंगे?",
    resetPasswordByEmail:
      "हम आपको पासवर्ड रीसेट करने के निर्देशों के साथ एक ईमेल भेजेंगे।",
    resetPasswordByText:
      "हम आपको पासवर्ड रीसेट करने के निर्देशों के साथ एक टेक्स्ट संदेश भेजेंगे।",
    enterValidPhoneNumber: "कृपया एक वैध फोन नंबर दर्ज करें।",
    enterValidEmailAndMobile: "कृपया एक मान्य ईमेल या फोन नंबर दर्ज करें।",
    sendPasswordResetCode: "साइन-इन कोड भेजें",
    passwordUpdated: "पासवर्ड सफलतापूर्वक अपडेट हो गया।",
    signInCodeSent: "साइन-इन कोड आपके ईमेल पर भेजा गया है।",
    emailMe: "मुझे ईमेल करें",
    messageMe: "मुझे संदेश भेजें",
    choosePlan: "अपना प्लान चुनें",
    planDetails:
      "कोई प्रतिबद्धताएँ नहीं, कभी भी रद्द करें। Netflix पर सब कुछ एक ही कम कीमत पर। कोई विज्ञापन और कोई अतिरिक्त शुल्क नहीं।",
    skip: "Skip",
    chooseTheRightPlan: "अपने लिए सही प्लान चुनें",
    choosePlanTitle: "अपना प्लान चुनें।",
    paymentSecurityInfo:
      "आपका भुगतान एन्क्रिप्ट किया गया है और आप कभी भी अपना भुगतान तरीका बदल सकते हैं।",
    securePeaceOfMind: "शांति के लिए सुरक्षित।",
    cancelEasilyOnline: "ऑनलाइन आसानी से रद्द करें।",
    endToEndEncrypted: "एंड-टू-एंड एन्क्रिप्टेड",
    creditOrDebitCard: "क्रेडिट या डेबिट कार्ड",
    upiAutoPay: "UPI ऑटोपे",
    paymentCompleted: "भुगतान पूरा हो गया",
    readyToWatch: "देखने के लिए तैयार!",
    whoIsWatching: "कौन देख रहा है?",
    addProfile: "प्रोफ़ाइल जोड़ें",
    manageProfiles: "प्रोफ़ाइल प्रबंधित करें",
    browse: "ब्राउज़ करें",
    signOut: "नेटफ्लिक्स से साइन आउट करें",
    serviceCode: "सर्विस कोड",
    play: "प्ले करें",
    moreInfo: "अधिक जानकारी",
    myList: "मेरा सूची",
    noTitlesInList: "आपने अभी तक अपनी सूची में कोई शीर्षक नहीं जोड़ा है।",
    removedFromList: "मेरी सूची से हटा दिया गया है।",
    undo: "पूर्ववत करें",
    netflixIndia: "नेटफ्लिक्स इंडिया",
    signout: "साइन आउट करें",
    finishSettingUpAccount: "अपना खाता सेटअप करना पूरा करें",
    personalizedNetflix:
      "नेटफ्लिक्स आपके लिए निजीकरण किया गया है। किसी भी डिवाइस पर कभी भी देखने के लिए एक पासवर्ड बनाएं।",
    next: "आगे",
    createPasswordNetflix: "अपनी सदस्यता शुरू करने के लिए एक पासवर्ड बनाएं।",
    fewStepsNetflix: "बस कुछ ही कदम और, और आप पूरा कर लेंगे!",
    paperworkNetflix: "हमें भी कागजी काम पसंद नहीं है।",
    emailOrMobileNetflix: "ईमेल या मोबाइल नंबर",
    passwordNetflix: "पासवर्ड",
    verifyEmailNetflix: "बहुत बढ़िया, अब हम आपका ईमेल सत्यापित करेंगे।",
    messageDataRatesNetflix: "संदेश और डेटा शुल्क लागू हो सकते हैं",
    orNetflix: "या",
    usePasswordNetflix: "पासवर्ड का उपयोग करें",
    useSignInCodeNetflix: "साइन-इन कोड का उपयोग करें",
    rememberMeNetflix: "मुझे याद रखें",
    newToNetflix: "क्या आप नेटफ्लिक्स पर नए हैं?",
    signUpNowNetflix: "अभी साइन अप करें",
    recaptchaProtectionNetflix:
      "यह पृष्ठ Google reCAPTCHA द्वारा सुरक्षित है ताकि यह सुनिश्चित किया जा सके कि आप बॉट नहीं हैं।",
    learnMoreNetflix: "और जानें।",
    updatePasswordEmailPhoneNetflix: "पासवर्ड, ईमेल या फोन अपडेट करें",
    textMessageSMS: "संदेश (SMS)",
    verificationCodeMessage:
      "हम आपको अपना पासवर्ड रीसेट करने के लिए एक सत्यापन कोड भेजेंगे। संदेश और डेटा दरें लागू हो सकती हैं।",
    mobileNumber: "मोबाइल नंबर",
    step: "चरण",
    of: "/",
    verifyingEmailMessage:
      "आपका ईमेल सत्यापित करने से खाता सुरक्षा में सुधार होगा और आपको महत्वपूर्ण Netflix संचार प्राप्त करने में मदद मिलेगी।",
  },
};

export default languageData;
